<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="jagadeesh" ignored="3" name="Default test" tests="1" failures="1" timestamp="14 May 2019 09:11:31 GMT" time="189.223" errors="0">
  <testcase name="Verify_Deleted_Offer_Is_Not_Present_In_CSV" time="189.12" classname="regressionTests.RegressionCases">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at driver.ActionClass.checkboxSelect(ActionClass.java:919)
at driver.DriverEngine.mainMethod(DriverEngine.java:261)
at regressionTests.RegressionCases.Verify_Deleted_Offer_Is_Not_Present_In_CSV(RegressionCases.java:109)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_Deleted_Offer_Is_Not_Present_In_CSV -->
  <testcase name="Verify_DownloadedCSV_For_New_version" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_DownloadedCSV_For_New_version -->
  <testcase name="Verify_DownloadedCSV_For_Existing_Version" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_DownloadedCSV_For_Existing_Version -->
  <testcase name="Verify_RealTimeEvent_API_Response_For_NewEvent" time="0.0" classname="regressionTests.RegressionCases">
    <ignored/>
  </testcase> <!-- Verify_RealTimeEvent_API_Response_For_NewEvent -->
</testsuite> <!-- Default test -->
